### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by flooie** [phihag/pdfform.js#1]
Would you be able to put together an example usage for this?

**Comment by phihag** [comment]
Thank you very much for the report! You can already find a basic example [in the tests](https://github.com/phihag/pdfform.js/blob/master/test/test_pdfform.js). I'll try to embellish the test into a formal example and improve the installation and startup experience within the next days.

**Comment by flooie** [comment]
Thank you!

**Comment by phihag** [comment]
Sorry for the delay; I've updated quite a lot and written a full-fledged demo: https://phihag.github.io/pdfform.js/docs/demo.html , as well as a rough [README](https://github.com/phihag/pdfform.js/blob/master/README.md). If you have any questions, please don't hesitate to ask. Thank you!

**Comment by flooie** [comment]
Thank you so much @phihag  - You're work is fantastic.
