### ISSUE TITLE
error in using npm package

### ISSUE THREAD

**Issue by JasonElting** [phihag/pdfform.js#18]
I'm still new to javascript to bear with me, but when I use the npm package, imported like this
```import * as pdfform from 'pdfform.js';```
 it get this error:
```
ERROR in ./node_modules/pdfform.js/dist/pdfform.minipdf.dist.js
Module not found: Error: Can't resolve './minipdf.js' in 'C:\Users\Jason\git\dev\globalflyte-webapp\node_modules\pdfform.js\dist'
ERROR in ./node_modules/pdfform.js/dist/pdfform.minipdf.dist.js
Module not found: Error: Can't resolve './minipdf_js.js' in 'C:\Users\Jason\git\dev\globalflyte-webapp\node_modules\pdfform.js\dist'
```

but everything is fixed when i just copy everything into /dist/ like this:
![capture](https://user-images.githubusercontent.com/3838139/45304979-5d444380-b4e7-11e8-8d0e-74bc2f06adea.PNG)

I think this is either an error with the npm package or I'm doing something wrong.

**Comment by smettu007** [comment]
go through README to use this lib in browser,  https://github.com/phihag/pdfform.js/blob/master/README.md

PS: im using this lib in nodejs

**Comment by JasonElting** [comment]
ok I figured it out, I had to change the import I think using angular does mess with the importing.

**Comment by jmstark** [comment]
> ok I figured it out, I had to change the import I think using angular does mess with the importing.
> thanks

Jason, could you please tell me what you had to change? I'm having the same issue. Thanks in advance!

**Comment by jmstark** [comment]
Thank you Jason!
The following also worked for me:

In `.angular-cli.json`, put the dist-file into the `scripts` section:
```
       "scripts": [
        "../node_modules/pdfform.js/dist/pdfform.minipdf.dist.js"
       ],
```

Add the exported symbol in `typings.d.ts`:
`declare var pdfform: any;`

Then, in the target TS file, do not import anything, just use it like this:
```
pdfform.transform(pdfDoc, fillValues);
```

However, with this method I couldn't figure out how to use `list_fields()` as it isn't exported as it seems. As I don't need it anyway it doesn't matter for me.

**Comment by leavesoftea** [comment]
@jmstark If you add the below line under the // Backwards compatibility only section (whatever that means) at line number 503 of pdfform.js you will be able to access list_fields in the same way as transform.

pdfform.list_fields = function(data) {return pdfform().list_fields(data);};
