### ISSUE TITLE
PDF Types

### ISSUE THREAD

**Issue by flooie** [phihag/pdfform.js#2]
I have been unable to use any of my own PDFs - built from scratch or already available.  Are there parameters or pdf version requirements?

**Comment by phihag** [comment]
No, basically every PDF should work. Can you post one or more examples? Did you use pdf.js or minipdf? How were you *unable*, i.e. did you get an error, or were the forms ignored, or what happened?

**Comment by flooie** [comment]
Forgive my delay in responding, I'm trying to diagnosis the problem on my end before I bother you about this.  But I get the following - and variations of them.


![Uploading Screen Shot 2016-09-09 at 2.20.18 PM.png…]()
![screen shot 2016-09-11 at 12 59 57 pm](https://cloud.githubusercontent.com/assets/6464529/18440542/8d4e8534-78d7-11e6-8ef7-5443dd1d0b2f.png)

**Comment by phihag** [comment]
Can you upload one of these PDF files somewhere, or alternatively, send it to phihag@phihag.de ? Does the problem occur when you select PDF.js in the demo?

**Comment by phihag** [comment]
Fixed in pdfform.js version 1.0.2, which now supports both types of documents you sent me.

**Comment by ustincameron** [comment]
I have this same issue with 3 of the 4 forms I'm attempting to solve. What's the best pdf version to save as? Trying to use pdf.js with 1.6 and 1.4 at the moment.
