### ISSUE TITLE
Missing Trailer

### ISSUE THREAD

**Issue by bestickley** [phihag/pdfform.js#8]
Hi, when I load my pdf into the online demo, I get any error saying I have a missing trailer. I've found a trailer in my pdf. Any ideas?

**Comment by bestickley** [comment]
Issue was fixed using PDF.js option

**Comment by phihag** [comment]
I'd be happy to fix it in minipdf.js as well. Can you upload the problematic PDF file somewhere or send it to phihag@phihag.de ?

**Comment by bestickley** [comment]
Thank you! I've sent you an email.
